version: '3.8'

services:
  fluentbit-master:
    build:
      context: ./collector/master
    ports:
      - "2021:2021"
    depends_on:
      - clickhouse

  vector:
    image: timberio/vector:latest-alpine
    ports:
      - "8686:8686"  # interface web Vector optionnelle
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - fluentbit-master
      - clickhouse
      
  clickhouse:
    build:
      context: ./collector/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/config.d/local_paths.xml:/etc/clickhouse-server/config.d/local_paths.xml:ro
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

      
volumes:
  clickhouse-data:
  clickhouse-logs:
