version: '3.8'

services:
  fluentbit-master:
    build:
      context: ./collector/master
    ports:
      - "2021:2021"
    depends_on:
      - clickhouse

  vector:
    image: timberio/vector:latest-alpine
    ports:
      - "8686:8686"  # interface web Vector optionnelle
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - fluentbit-master
      - clickhouse
      
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"

      
volumes:
  clickhouse-data:
  clickhouse-logs:
