version: '3.8'

services:
  fluentbit-worker:
    build:
      context: ./collector/worker
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/containers:/var/log/containers:ro
    environment:
      - FLUENTBIT_MASTER_HOST=89.116.38.238
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
