version: '3.8'

services:
  fluentbit-master:
    image: fluent/fluent-bit:latest
    volumes:
      - /var/log/:/var/log/:ro
      - ./collector/fluent-bit-master.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./collector/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    environment:
      - FLUENTBIT_MASTER_HOST=89.116.38.238
    ports:
      - "2021:2021"
    depends_on:
      - clickhouse

  vector:
    image: timberio/vector:latest-alpine
    ports:
      - "8686:8686"  # interface web Vector optionnelle
      - "24224:24224"  # port de sortie pour Fluent Bit
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - fluentbit-master
      - clickhouse
      
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"

      
volumes:
