version: '3.8'

services:
  fluentbit-worker:
    build:
      context: ./collector/worker
    volumes:
      - /var/log/:/var/log/:ro
    environment:
      - FLUENTBIT_MASTER_HOST=89.116.38.238
    comand: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit-worker.conf
    ports:
      - "2021:2021"                             

