version: '3.8'

services:
  fluentbit-master:
    build:
      context: ./master
    ports:
      - "2021:2021"
    depends_on:
      - clickhouse

  vector:
    image: timberio/vector:latest-alpine
    ports:
      - "8686:8686"  # interface web Vector optionnelle
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - fluentbit-master
      - clickhouse
      
  clickhouse:
    build:
      context: ./clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
