# vector.toml
[sources.fluentbit]
type = "socket"
address = "0.0.0.0:24224"
mode = "tcp"

[transforms.parse_json]
type = "remap"
inputs = ["fluentbit"]
source = '''
structured = parse_json!(.message)
'''

[sinks.clickhouse]
type = "clickhouse"
inputs = ["parse_json"]
endpoint = "http://89.116.38.238:8123"
database = "default"
table = "logs"
compression = "gzip"

[sinks.clickhouse.encoding]
codec = "json"

[sinks.console]
type = "console"
inputs = ["parse_json"]
target = "stdout"
encoding.codec = "json"
