# vector/vector.toml

[sources.fluentbit]
type = "fluent"
address = "0.0.0.0"
port = 24224
mode = "tcp"

[transforms.parse_json]
type = "remap"
inputs = ["fluentbit"]
source = '''
structured = parse_json!(.message)
'''

[sinks.console]
type = "console"
inputs = ["fluentbit"]
target = "stdout"
encoding.codec = "json"
